### ISSUE TITLE
Socket Dupe Bug

### ISSUE THREAD

**Issue by applessmillion** [Nunnery/MythicDrops#288] opened 2016-06-08 03:40 UTC
When you place an item in your off-hand slot on a 1.9 server that is socketable, then right-click on a socket, the socket will be used and a duplicated version of the weapon/tool/armorpiece will be placed in the socket's place.
![gif](https://cloud.githubusercontent.com/assets/18158365/15882014/234e7550-2d09-11e6-8d7b-bda2d1d1f758.gif)

Both items get the socket, too.

**Comment by Nunnery** [comment] 2016-06-08 15:12
Duplicate of #279. Solved in development builds available at http://build.tealcubegames.com/.

**Closed by Nunnery** 2016-06-08 15:12 UTC
